package lk.Ijse.db;

public enum RestaurantEventType {
    BIRTHDAY_PARTY,
    FAMILY_GATHERING,
    OFFICE_PARTY,
    FRIENDS_OUTING,
    CELEBRATION,
    CORPORATE_EVENT,
    TEAM_BUILDING,
    REUNION,
    GRADUATION_CELEBRATION,
    HOLIDAY_GATHERING,
    ENGAGEMENT_PARTY,
    ANNIVERSARY_CELEBRATION
}
